#! /bin/sh



pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d IV V VI VII VIII IX X
bspc monitor VGA-0  -d I II III

bspc config border_width         1
bspc config window_gap           2

# Border colors
bspc config normal_border_color "#90E7F7"
bspc config focused_border_color "#FD971F"
bspc config urgent_border_color "#F92672"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
